### REGISTER USER
POST http://localhost:5000/api/auth/register HTTP/1.1
Content-Type: application/json

{"username":"nicolas","email":"asd@asd.com", "password":"123456"}


### CART CREATE
POST http://localhost:5000/api/carts HTTP/1.1
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxODQ1ODUyZjQ0MGViM2RhMmQ1ZThhOCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzkwOTQxODYsImV4cCI6MTYzOTM1MzM4Nn0.5OSyAFWgEM69LmtIShqVHbASaYmf-WOzCaXp1xY1uD0
Content-Type: application/json

{"userId":"61845852f440eb3da2d5e8a8"}

### CART GET USER CART
GET http://localhost:5000/api/carts/find/61845852f440eb3da2d5e8a8
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxODQ1ODUyZjQ0MGViM2RhMmQ1ZThhOCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzkwMDMyNDYsImV4cCI6MTYzOTI2MjQ0Nn0.CAPQBC_crNevlt4bcAPX3tmq5PhowpDncdjU7iIuXHI
Content-Type: application/json

### CART UPDATE
PUT http://localhost:5000/api/carts/61845852f440eb3da2d5e8a8 HTTP/1.1
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxODQ1ODUyZjQ0MGViM2RhMmQ1ZThhOCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzkwMDMyNDYsImV4cCI6MTYzOTI2MjQ0Nn0.CAPQBC_crNevlt4bcAPX3tmq5PhowpDncdjU7iIuXHI
Content-Type: application/json

{"products":
[{"productId":"61843ee7a7a1a5ebbfca12d6",
 "size":"S",
 "color":"white",
"quantity":1},{"productId":"61843ee7a7a1a5ebbfca12d6",
 "size":"S",
 "color":"white",
"quantity":1}]
}


### CART UPDATE TEST
PUT http://localhost:5000/api/carts/61845852f440eb3da2d5e8a8 HTTP/1.1
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxODQ1ODUyZjQ0MGViM2RhMmQ1ZThhOCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzkwNjUxOTUsImV4cCI6MTYzOTMyNDM5NX0.Vn4xMe_meEkXETgYawJKSdKpkqTDYnfwiymKOmTJv1k
Content-Type: application/json

{"products":[
{"$productId":"61843ee7a7a1a5ebbfca12d6",
"img":"https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
"title":"asd",
"price":19,
"size":"S",
"color":"white",
"quantity":1}
]}

### TEST
GET http://localhost:5000/api/carts/test HTTP/1.1
# token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxODQ1ODUyZjQ0MGViM2RhMmQ1ZThhOCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzkwNjUxOTUsImV4cCI6MTYzOTMyNDM5NX0.Vn4xMe_meEkXETgYawJKSdKpkqTDYnfwiymKOmTJv1k
Content-Type: application/json

{"userId":"61845852f440eb3da2d5e8a8", "$and": [{"products._id":"61b29aa35957363923d69995"},{"products.size":"S"},{"products.color":"orange"}]}

### TEST2
GET http://172.27.28.198:5000/api/carts/test HTTP/1.1
# token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxODQ1ODUyZjQ0MGViM2RhMmQ1ZThhOCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzkwNjUxOTUsImV4cCI6MTYzOTMyNDM5NX0.Vn4xMe_meEkXETgYawJKSdKpkqTDYnfwiymKOmTJv1k
Content-Type: application/json

{"userId":"61845852f440eb3da2d5e8a8", "$and": [{"products._id":"61b29aa35957363923d69995"},{"products.size":"S"},{"products.color":"orange"}]}




# {"userId":"61845852f440eb3da2d5e8a8","products._id":"61b29aa35957363923d69995"}

# {"products.$":1}

# {"products":[]}